import Head from 'next/head'
import { Roboto, Barlow } from 'next/font/google'

const fontRoboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
})

const fontBarlow = Barlow({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-barlow',
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${fontRoboto.variable} ${fontBarlow.variable}`}>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum, saepe enim.
          Placeat, unde porro, accusamus vel voluptatibus illum minima temporibus aperiam
          pariatur quia voluptas, nobis vitae eveniet velit doloribus nemo?
        </p>
      </main>
    </>
  )
}
